version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fastapi_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3305:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  api:
    build: .
    container_name: fastapi_container
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3305
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: fastapi_db

volumes:
  db_data: