version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fastapi_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: hydra
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: hydra
    ports:
      - "5432:5432"
    volumes:
      - hydra-data:/var/lib/postgresql/data

  hydra-migrate:
    image: oryd/hydra:v2.2
    depends_on:
      - postgres
    environment:
      - DSN=postgres://hydra:1234@postgres:5432/hydra?sslmode=disable
    command: migrate sql -e --yes

  hydra-admin:
    image: oryd/hydra:v2.2
    depends_on:
      - hydra-migrate
    environment:
      - DSN=postgres://hydra:1234@postgres:5432/hydra?sslmode=disable
      - URLS_SELF_ISSUER=http://hydra-public:4444
      - SECRETS_SYSTEM=thishshouldbeverylong
    command: serve admin --dev
    ports:
      - "4445:4445"

  hydra-public:
    image: oryd/hydra:v2.2
    depends_on:
      - hydra-migrate
    environment:
      - DSN=postgres://hydra:1234@postgres:5432/hydra?sslmode=disable
      - URLS_SELF_ISSUER=http://hydra-public:4444
      - SECRETS_SYSTEM=thishshouldbeverylong
    command: serve public --dev
    ports:
      - "4444:4444"

  api:
    build: .
    container_name: fastapi_container
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - hydra-admin
      - hydra-public
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3307
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: fastapi_db
      AUTH_ISSUER: http://hydra-public:4444

volumes:
  db_data:
  hydra-data:

networks:
  default:
    name: hydra-net
